name: Saludos

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Intentare Solucionar los problemas que se presenten lo antes posible,Gracias por tu tiempo y comprension."
        pr-message: "Puedes Bifurcar o Extraer el Repositorio,solo pido que me nombres,menciones,Hagamos crecer este proyecto"
